modLoader="javafml"
loaderVersion="[47,)"  # 匹配Forge 47.4.0
license="All Rights Reserved"

[[mods]]
modId="seaborn_invasion"  # 必须全小写
version="1.0.0"
displayName="Seaborn Invasion"
authors="YourName"
description='''
添加明日方舟海嗣生物以及对应事件到Minecraft中
'''

[[dependencies.seaborn_invasion]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)" 

[[dependencies.seaborn_invasion]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"